// src/scheduling/enums/session-status.enum.ts
export enum SessionStatus {
  SCHEDULED = 'SCHEDULED',
  PENDING_MODIFICATION = 'PENDING_MODIFICATION',
  CANCELLED_BY_STUDENT = 'CANCELLED_BY_STUDENT',
  CANCELLED_BY_TUTOR = 'CANCELLED_BY_TUTOR',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN',
  COMPLETED = 'COMPLETED',
}