import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1700000000000 implements MigrationInterface {
    name = 'InitialSchema1700000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "fk_answers_question"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "fk_answers_student_session"`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" DROP CONSTRAINT "fk_student_participate_session_student"`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" DROP CONSTRAINT "fk_student_participate_session_session"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" DROP CONSTRAINT "fk_modification_requests_session"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" DROP CONSTRAINT "fk_modification_requests_requester"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" DROP CONSTRAINT "fk_modification_requests_responder"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "fk_sessions_tutor"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "fk_sessions_subject"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "fk_scheduled_sessions_tutor"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "fk_scheduled_sessions_availability"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "fk_scheduled_sessions_session"`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" DROP CONSTRAINT "fk_tha_tutor"`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" DROP CONSTRAINT "fk_tha_availability"`);
        await queryRunner.query(`ALTER TABLE "tutors" DROP CONSTRAINT "fk_tutor_user"`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" DROP CONSTRAINT "fk_tutor_subject_tutor"`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" DROP CONSTRAINT "fk_tutor_subject_subject"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "fk_students_user"`);
        await queryRunner.query(`ALTER TABLE "dashboard_banner" DROP CONSTRAINT "fk_dashboard_banner_updated_by"`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "fk_auth_session_user"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "fk_reset_user"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "fk_verify_user"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "fk_audit_user"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "fk_audit_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_questions_aspect"`);
        await queryRunner.query(`DROP INDEX "public"."idx_questions_is_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_questions_display_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_questions_questionnaire_version"`);
        await queryRunner.query(`DROP INDEX "public"."idx_answers_id_student"`);
        await queryRunner.query(`DROP INDEX "public"."idx_answers_id_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_answers_evaluation_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_answers_evaluated_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_student_participate_session_student"`);
        await queryRunner.query(`DROP INDEX "public"."idx_student_participate_session_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_student_participate_session_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_student_participate_session_arrival_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_student_participate_session_status_arrival"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_requests_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_requests_requester"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_requests_responder"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_requests_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_requests_requested_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_requests_pending_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_expiry"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scheduled_sessions_id_tutor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scheduled_sessions_id_availability"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scheduled_sessions_id_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scheduled_sessions_composite"`);
        await queryRunner.query(`DROP INDEX "public"."idx_students_career"`);
        await queryRunner.query(`DROP INDEX "public"."idx_students_preferred_modality"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_locked"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_sessions_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_sessions_expires"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_sessions_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reset_expires"`);
        await queryRunner.query(`DROP INDEX "public"."ux_reset_active_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_verify_expires"`);
        await queryRunner.query(`DROP INDEX "public"."ux_verify_active_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_notifications_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_notifications_user_read"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_notifications_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_app_notifications_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_failed_logins"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" DROP CONSTRAINT "chk_response_consistency"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" DROP CONSTRAINT "chk_expires_after_request"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "chk_session_times"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "chk_sessions_max_participants"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_check"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_status_check"`);
        await queryRunner.query(`ALTER TABLE "dashboard_banner" DROP CONSTRAINT "chk_dashboard_banner_single_row"`);
        await queryRunner.query(`COMMENT ON TABLE "questions" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "answers" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "student_participate_session" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "session_modification_requests" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "dashboard_banner" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "app_notifications" IS NULL`);
        await queryRunner.query(`CREATE TABLE "student_interested_subject" ("id_student" uuid NOT NULL, "id_subject" uuid NOT NULL, CONSTRAINT "PK_7669f9531866a26d5eecf993e01" PRIMARY KEY ("id_student", "id_subject"))`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."id_question" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."content" IS NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "aspect" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."aspect" IS NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "label" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."label" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."description" IS NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "required" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."required" IS NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "display_order" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."display_order" IS NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "min_score" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."min_score" IS NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "max_score" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."max_score" IS NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "questionnaire_version" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."questionnaire_version" IS NULL`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."is_active" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."id_question" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."id_student" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."id_session" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."evaluation_id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."score" IS NULL`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "evaluated_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."evaluated_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "evaluated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "questionnaire_version" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."questionnaire_version" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."id_student" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."id_session" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."participation_status_enum" RENAME TO "participation_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."student_participate_session_status_enum" AS ENUM('CONFIRMED', 'ATTENDED', 'ABSENT', 'LATE')`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ALTER COLUMN "status" TYPE "public"."student_participate_session_status_enum" USING "status"::"text"::"public"."student_participate_session_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."participation_status_enum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."comment" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."arrival_time" IS NULL`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ALTER COLUMN "joined_at" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."id_request" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."id_session" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."requested_by" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."new_scheduled_date" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."new_start_time" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."session_modality_enum" RENAME TO "session_modality_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."session_modification_requests_new_modality_enum" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "new_modality" TYPE "public"."session_modification_requests_new_modality_enum" USING "new_modality"::"text"::"public"."session_modification_requests_new_modality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."session_modality_enum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."new_modality" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."new_duration_hours" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."modification_status_enum" RENAME TO "modification_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."session_modification_requests_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "status" TYPE "public"."session_modification_requests_status_enum" USING "status"::"text"::"public"."session_modification_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."modification_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "requested_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."requested_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "requested_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."responded_at" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."responded_by" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."expires_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "description" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."session_type_enum" RENAME TO "session_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sessions_type_enum" AS ENUM('INDIVIDUAL', 'GROUP')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "type" TYPE "public"."sessions_type_enum" USING "type"::"text"::"public"."sessions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."session_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."session_modality_enum" RENAME TO "session_modality_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sessions_modality_enum" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "modality" TYPE "public"."sessions_modality_enum" USING "modality"::"text"::"public"."sessions_modality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."session_modality_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "modality" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "virtual_link"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "virtual_link" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_enum" RENAME TO "session_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sessions_status_enum" AS ENUM('PENDING_TUTOR_CONFIRMATION', 'SCHEDULED', 'PENDING_MODIFICATION', 'REJECTED_BY_TUTOR', 'CANCELLED_BY_STUDENT', 'CANCELLED_BY_TUTOR', 'CANCELLED_BY_ADMIN', 'COMPLETED', 'EXPIRED_UNCONFIRMED')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" TYPE "public"."sessions_status_enum" USING "status"::"text"::"public"."sessions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" SET DEFAULT 'SCHEDULED'`);
        await queryRunner.query(`DROP TYPE "public"."session_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" SET DEFAULT 'SCHEDULED'`);
        await queryRunner.query(`COMMENT ON COLUMN "sessions"."confirmation_expires_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "cancelled_within_24h" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "tutor_confirmed" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."tutor_have_availability_modality_enum" RENAME TO "tutor_have_availability_modality_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_have_availability_modality_enum" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" ALTER COLUMN "modality" TYPE "public"."tutor_have_availability_modality_enum"[] USING "modality"::"text"::"public"."tutor_have_availability_modality_enum"[]`);
        await queryRunner.query(`DROP TYPE "public"."tutor_have_availability_modality_enum_old"`);
        await queryRunner.query(`ALTER TABLE "tutors" ALTER COLUMN "limit_disponibility" SET DEFAULT '8'`);
        await queryRunner.query(`ALTER TABLE "students" ALTER COLUMN "profile_completed" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."preferred_modality_enum" RENAME TO "preferred_modality_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."students_preferred_modality_enum" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`ALTER TABLE "students" ALTER COLUMN "preferred_modality" TYPE "public"."students_preferred_modality_enum" USING "preferred_modality"::"text"::"public"."students_preferred_modality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."preferred_modality_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('STUDENT', 'TUTOR', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'PENDING', 'BLOCKED')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ALTER COLUMN "id_user" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."user_id" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."app_notification_type" RENAME TO "app_notification_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."app_notifications_type_enum" AS ENUM('SESSION_REQUEST_RECEIVED', 'SESSION_REQUEST_ACK', 'SESSION_CONFIRMED', 'SESSION_REJECTED', 'SESSION_CANCELLED', 'MODIFICATION_REQUEST', 'MODIFICATION_ACCEPTED', 'MODIFICATION_REJECTED', 'SESSION_DETAILS_UPDATED', 'SESSION_REMINDER_24H', 'SESSION_REMINDER_2H', 'EVALUATION_PENDING', 'EVALUATION_REMINDER', 'AVAILABILITY_CHANGED', 'HOUR_LIMIT_ALERT', 'SESSION_ABSENT')`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ALTER COLUMN "type" TYPE "public"."app_notifications_type_enum" USING "type"::"text"::"public"."app_notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."app_notification_type_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."type" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."message" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."payload" IS NULL`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ALTER COLUMN "read" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."read" IS NULL`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."created_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."audit_action" RENAME TO "audit_action_old"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'ACCOUNT_CREATED', 'EMAIL_VERIFIED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'SESSION_CREATED', 'SESSION_REFRESHED', 'SESSION_REVOKED', 'SESSION_EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "public"."audit_logs_action_enum" USING "action"::"text"::"public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_action_old"`);
        await queryRunner.query(`ALTER TYPE "public"."audit_result" RENAME TO "audit_result_old"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_result_enum" AS ENUM('SUCCESS', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "result" TYPE "public"."audit_logs_result_enum" USING "result"::"text"::"public"."audit_logs_result_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_result_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_0ba1a7b7a3221b68b9b89f00ad" ON "app_notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_47db88381f4401f7c35b58ec7a" ON "app_notifications" ("user_id", "read") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0ba28fb988d154f68de8cad77" ON "app_notifications" ("user_id", "created_at") `);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "UQ_tutor_availability_date" UNIQUE ("id_tutor", "id_availability", "scheduled_date")`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_c570b5fef77654bf9ff41b00624" FOREIGN KEY ("id_question") REFERENCES "questions"("id_question") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_a34388d454fcfb0f90b6ff4b515" FOREIGN KEY ("id_student", "id_session") REFERENCES "student_participate_session"("id_student","id_session") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ADD CONSTRAINT "FK_049762489deb773f79eaa38e43b" FOREIGN KEY ("id_student") REFERENCES "students"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ADD CONSTRAINT "FK_fe4bfc9c9d6054067ca1490a5a3" FOREIGN KEY ("id_session") REFERENCES "sessions"("id_session") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ADD CONSTRAINT "FK_1261036d0c45dda8eb7c43bd1a1" FOREIGN KEY ("id_session") REFERENCES "sessions"("id_session") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ADD CONSTRAINT "FK_8b3e850804222a5cab0b51158e7" FOREIGN KEY ("requested_by") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ADD CONSTRAINT "FK_703383a4c0a87bbcd10f9dde19f" FOREIGN KEY ("responded_by") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_a9ed75a85efcadd71bbc8be5ee5" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_412317c2f4613f7f852ec0eaf31" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "FK_0d4b04a7079847403da2f7587cd" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "FK_c862ed5f3d65ee0ab41aa0c6fd6" FOREIGN KEY ("id_availability") REFERENCES "availability"("id_availability") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "FK_6df0305f4681b7af345413ee6d7" FOREIGN KEY ("id_session") REFERENCES "sessions"("id_session") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" ADD CONSTRAINT "FK_6fe15be85a142eb123e22c9d043" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" ADD CONSTRAINT "FK_1b75a22ce69dd4ad3eafb4ccf2f" FOREIGN KEY ("id_availability") REFERENCES "availability"("id_availability") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutors" ADD CONSTRAINT "FK_8325796beb64a4c91dfe1c3955b" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" ADD CONSTRAINT "FK_a11475cea15ad0c4faa5e7ade16" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" ADD CONSTRAINT "FK_e2a77eea1cf449be7efe7147b31" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_interested_subject" ADD CONSTRAINT "FK_fa1094cb4cc067b455c39fa4ac8" FOREIGN KEY ("id_student") REFERENCES "students"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_interested_subject" ADD CONSTRAINT "FK_36ba92aa42c5d6d14eca4ac8028" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_b559710a42d2bf3b49062750132" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dashboard_banner" ADD CONSTRAINT "FK_c22b522545cf70676b3b26f193c" FOREIGN KEY ("updated_by") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "FK_b266e81e60e8c49ae2eb7c46d27" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_a440159fb2d7b579070f5206044" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_8e4afd15aa5933a0aef14ddc743" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_1aabbc22a9f345c55ee39bf5daf" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_25d884c2a4c2cb629dc994e82d1" FOREIGN KEY ("id_session") REFERENCES "auth_sessions"("id_session") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_25d884c2a4c2cb629dc994e82d1"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_1aabbc22a9f345c55ee39bf5daf"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_8e4afd15aa5933a0aef14ddc743"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_a440159fb2d7b579070f5206044"`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "FK_b266e81e60e8c49ae2eb7c46d27"`);
        await queryRunner.query(`ALTER TABLE "dashboard_banner" DROP CONSTRAINT "FK_c22b522545cf70676b3b26f193c"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_b559710a42d2bf3b49062750132"`);
        await queryRunner.query(`ALTER TABLE "student_interested_subject" DROP CONSTRAINT "FK_36ba92aa42c5d6d14eca4ac8028"`);
        await queryRunner.query(`ALTER TABLE "student_interested_subject" DROP CONSTRAINT "FK_fa1094cb4cc067b455c39fa4ac8"`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" DROP CONSTRAINT "FK_e2a77eea1cf449be7efe7147b31"`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" DROP CONSTRAINT "FK_a11475cea15ad0c4faa5e7ade16"`);
        await queryRunner.query(`ALTER TABLE "tutors" DROP CONSTRAINT "FK_8325796beb64a4c91dfe1c3955b"`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" DROP CONSTRAINT "FK_1b75a22ce69dd4ad3eafb4ccf2f"`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" DROP CONSTRAINT "FK_6fe15be85a142eb123e22c9d043"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "FK_6df0305f4681b7af345413ee6d7"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "FK_c862ed5f3d65ee0ab41aa0c6fd6"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "FK_0d4b04a7079847403da2f7587cd"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_412317c2f4613f7f852ec0eaf31"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_a9ed75a85efcadd71bbc8be5ee5"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" DROP CONSTRAINT "FK_703383a4c0a87bbcd10f9dde19f"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" DROP CONSTRAINT "FK_8b3e850804222a5cab0b51158e7"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" DROP CONSTRAINT "FK_1261036d0c45dda8eb7c43bd1a1"`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" DROP CONSTRAINT "FK_fe4bfc9c9d6054067ca1490a5a3"`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" DROP CONSTRAINT "FK_049762489deb773f79eaa38e43b"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_a34388d454fcfb0f90b6ff4b515"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_c570b5fef77654bf9ff41b00624"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "UQ_tutor_availability_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0ba28fb988d154f68de8cad77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47db88381f4401f7c35b58ec7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ba1a7b7a3221b68b9b89f00ad"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_result_old" AS ENUM('SUCCESS', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "result" TYPE "public"."audit_result_old" USING "result"::"text"::"public"."audit_result_old"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_result_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."audit_result_old" RENAME TO "audit_result"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_action_old" AS ENUM('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'ACCOUNT_CREATED', 'EMAIL_VERIFIED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'SESSION_CREATED', 'SESSION_REFRESHED', 'SESSION_REVOKED', 'SESSION_EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "public"."audit_action_old" USING "action"::"text"::"public"."audit_action_old"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."audit_action_old" RENAME TO "audit_action"`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."created_at" IS 'Fecha y hora de creación de la notificación'`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."read" IS 'Indica si la notificación ha sido leída por el usuario. false = no leída (punto azul)'`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ALTER COLUMN "read" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."payload" IS 'Datos mínimos para deep linking o acciones directas. Ej: { "sessionId": "uuid", "requestId": "uuid" }'`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."message" IS 'Texto legible listo para mostrar en el panel. Máximo 300 caracteres'`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."type" IS 'Tipo de notificación según las reglas funcionales del sistema'`);
        await queryRunner.query(`CREATE TYPE "public"."app_notification_type_old" AS ENUM('SESSION_REQUEST_RECEIVED', 'SESSION_REQUEST_ACK', 'SESSION_CONFIRMED', 'SESSION_REJECTED', 'SESSION_CANCELLED', 'MODIFICATION_REQUEST', 'MODIFICATION_ACCEPTED', 'MODIFICATION_REJECTED', 'SESSION_DETAILS_UPDATED', 'SESSION_REMINDER_24H', 'SESSION_REMINDER_2H', 'EVALUATION_PENDING', 'EVALUATION_REMINDER', 'AVAILABILITY_CHANGED', 'HOUR_LIMIT_ALERT')`);
        await queryRunner.query(`ALTER TABLE "app_notifications" ALTER COLUMN "type" TYPE "public"."app_notification_type_old" USING "type"::"text"::"public"."app_notification_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."app_notifications_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."app_notification_type_old" RENAME TO "app_notification_type"`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."user_id" IS 'ID del usuario destinatario. No es FK para evitar joins y permitir eliminación independiente'`);
        await queryRunner.query(`COMMENT ON COLUMN "app_notifications"."id" IS 'Identificador único de la notificación (UUID)'`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ALTER COLUMN "id_user" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(20) NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."preferred_modality_enum_old" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`ALTER TABLE "students" ALTER COLUMN "preferred_modality" TYPE "public"."preferred_modality_enum_old" USING "preferred_modality"::"text"::"public"."preferred_modality_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."students_preferred_modality_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."preferred_modality_enum_old" RENAME TO "preferred_modality_enum"`);
        await queryRunner.query(`ALTER TABLE "students" ALTER COLUMN "profile_completed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tutors" ALTER COLUMN "limit_disponibility" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_have_availability_modality_enum_old" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" ALTER COLUMN "modality" TYPE "public"."tutor_have_availability_modality_enum_old"[] USING "modality"::"text"::"public"."tutor_have_availability_modality_enum_old"[]`);
        await queryRunner.query(`DROP TYPE "public"."tutor_have_availability_modality_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."tutor_have_availability_modality_enum_old" RENAME TO "tutor_have_availability_modality_enum"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "tutor_confirmed" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "cancelled_within_24h" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "sessions"."confirmation_expires_at" IS 'Fecha y hora en que expira la confirmación del tutor. Si es NULL y status es PENDING_TUTOR_CONFIRMATION, nunca expira.'`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."session_status_enum_old" AS ENUM('SCHEDULED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'PENDING_MODIFICATION', 'REJECTED_BY_TUTOR', 'CANCELLED_BY_STUDENT', 'CANCELLED_BY_TUTOR', 'CANCELLED_BY_ADMIN', 'PENDING_TUTOR_CONFIRMATION', 'EXPIRED_UNCONFIRMED')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" TYPE "public"."session_status_enum_old" USING "status"::"text"::"public"."session_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_enum_old" RENAME TO "session_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "virtual_link"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "virtual_link" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD "location" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "modality" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."session_modality_enum_old" AS ENUM('PRES', 'VIRT', 'ONLINE')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "modality" TYPE "public"."session_modality_enum_old" USING "modality"::"text"::"public"."session_modality_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_modality_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_modality_enum_old" RENAME TO "session_modality_enum"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "type" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."session_type_enum_old" AS ENUM('INDIVIDUAL', 'GROUP')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "type" TYPE "public"."session_type_enum_old" USING "type"::"text"::"public"."session_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_type_enum_old" RENAME TO "session_type_enum"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "description" SET DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "title" SET DEFAULT ''`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."expires_at" IS 'Fecha de expiración (24h después de requested_at)'`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."responded_by" IS 'Usuario que respondió a la solicitud'`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."responded_at" IS 'Fecha y hora de la respuesta'`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "requested_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."requested_at" IS 'Fecha y hora de la solicitud'`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "requested_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."status" IS 'Estado de la solicitud: PENDING, APPROVED, REJECTED, EXPIRED'`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."modification_status_enum_old" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'ACCEPTED')`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "status" TYPE "public"."modification_status_enum_old" USING "status"::"text"::"public"."modification_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."session_modification_requests_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."modification_status_enum_old" RENAME TO "modification_status_enum"`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."new_duration_hours" IS 'Nueva duración propuesta en horas (con 1 decimal)'`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."new_modality" IS 'Nueva modalidad propuesta (opcional)'`);
        await queryRunner.query(`CREATE TYPE "public"."session_modality_enum_old" AS ENUM('PRES', 'VIRT', 'ONLINE')`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ALTER COLUMN "new_modality" TYPE "public"."session_modality_enum_old" USING "new_modality"::"text"::"public"."session_modality_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."session_modification_requests_new_modality_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_modality_enum_old" RENAME TO "session_modality_enum"`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."new_start_time" IS 'Nueva hora de inicio propuesta (opcional)'`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."new_scheduled_date" IS 'Nueva fecha propuesta (opcional)'`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."requested_by" IS 'Usuario que solicita la modificación'`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."id_session" IS 'Identificador de la sesión a modificar'`);
        await queryRunner.query(`COMMENT ON COLUMN "session_modification_requests"."id_request" IS 'Identificador UUID de la solicitud'`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ALTER COLUMN "joined_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."arrival_time" IS 'Hora de llegada del estudiante a la sesión'`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."comment" IS 'Comentario adicional sobre la participación'`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."status" IS 'Estado de participación del estudiante en la sesión'`);
        await queryRunner.query(`CREATE TYPE "public"."participation_status_enum_old" AS ENUM('CONFIRMED', 'PENDING', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'ABSENT', 'ATTENDED')`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ALTER COLUMN "status" TYPE "public"."participation_status_enum_old" USING "status"::"text"::"public"."participation_status_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."student_participate_session_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."participation_status_enum_old" RENAME TO "participation_status_enum"`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."id_session" IS 'Identificador de la sesión (parte de la clave primaria compuesta)'`);
        await queryRunner.query(`COMMENT ON COLUMN "student_participate_session"."id_student" IS 'Identificador del estudiante (parte de la clave primaria compuesta)'`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."questionnaire_version" IS 'Versión del cuestionario al momento de responder'`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "questionnaire_version" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "evaluated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."evaluated_at" IS 'Fecha y hora de evaluación'`);
        await queryRunner.query(`ALTER TABLE "answers" ALTER COLUMN "evaluated_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."score" IS 'Puntaje obtenido en la respuesta'`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."evaluation_id" IS 'Identificador de la evaluación'`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."id_session" IS 'Identificador de la sesión (parte de PK y FK)'`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."id_student" IS 'Identificador del estudiante (parte de PK y FK)'`);
        await queryRunner.query(`COMMENT ON COLUMN "answers"."id_question" IS 'Identificador de la pregunta (parte de PK y FK)'`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."is_active" IS 'Indica si la pregunta está activa'`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."questionnaire_version" IS 'Versión del cuestionario'`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "questionnaire_version" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."max_score" IS 'Puntaje máximo permitido'`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "max_score" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."min_score" IS 'Puntaje mínimo permitido'`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "min_score" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."display_order" IS 'Orden de visualización de la pregunta'`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "display_order" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."required" IS 'Indica si la pregunta es obligatoria'`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "required" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."description" IS 'Descripción adicional de la pregunta'`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."label" IS 'Etiqueta de la pregunta'`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "label" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."aspect" IS 'Aspecto evaluado (CLARITY, PATIENCE, PUNCTUALITY, KNOWLEDGE)'`);
        await queryRunner.query(`ALTER TABLE "questions" ALTER COLUMN "aspect" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."content" IS 'Contenido de la pregunta'`);
        await queryRunner.query(`COMMENT ON COLUMN "questions"."id_question" IS 'Identificador único de la pregunta (UUID)'`);
        await queryRunner.query(`DROP TABLE "student_interested_subject"`);
        await queryRunner.query(`COMMENT ON TABLE "app_notifications" IS 'Tabla que almacena las notificaciones push/in-app del sistema'`);
        await queryRunner.query(`COMMENT ON TABLE "dashboard_banner" IS 'Banner publicitario único mostrado en el dashboard de todos los usuarios. Solo existe una fila (id=1), gestionada exclusivamente por ADMIN.'`);
        await queryRunner.query(`COMMENT ON TABLE "session_modification_requests" IS 'Solicitudes de modificación de sesiones'`);
        await queryRunner.query(`COMMENT ON TABLE "student_participate_session" IS 'Tabla de relación entre estudiantes y sesiones (participación)'`);
        await queryRunner.query(`COMMENT ON TABLE "answers" IS 'Tabla que almacena las respuestas de los estudiantes'`);
        await queryRunner.query(`COMMENT ON TABLE "questions" IS 'Tabla que almacena las preguntas de los cuestionarios'`);
        await queryRunner.query(`ALTER TABLE "dashboard_banner" ADD CONSTRAINT "chk_dashboard_banner_single_row" CHECK ((id = 1))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_status_check" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PENDING'::character varying, 'BLOCKED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_check" CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'TUTOR'::character varying, 'ADMIN'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "chk_sessions_max_participants" CHECK (((max_participants IS NULL) OR ((max_participants >= 1) AND (max_participants <= 30))))`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "chk_session_times" CHECK ((end_time > start_time))`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ADD CONSTRAINT "chk_expires_after_request" CHECK ((expires_at > requested_at))`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ADD CONSTRAINT "chk_response_consistency" CHECK ((((responded_at IS NULL) AND (responded_by IS NULL)) OR ((responded_at IS NOT NULL) AND (responded_by IS NOT NULL))))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_failed_logins" ON "audit_logs" ("action", "created_at", "ip_address") WHERE (action = 'LOGIN_FAILED'::audit_action)`);
        await queryRunner.query(`CREATE INDEX "idx_audit_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_user" ON "audit_logs" ("id_user") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_created" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_app_notifications_type" ON "app_notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_app_notifications_created_at" ON "app_notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_app_notifications_user_read" ON "app_notifications" ("read", "user_id") WHERE (read = false)`);
        await queryRunner.query(`CREATE INDEX "idx_app_notifications_user_created" ON "app_notifications" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_verify_active_token" ON "email_verification_tokens" ("id_user") WHERE (verified_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_verify_expires" ON "email_verification_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_reset_active_token" ON "password_reset_tokens" ("id_user") WHERE (used_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_reset_expires" ON "password_reset_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_active" ON "auth_sessions" ("id_user") WHERE (revoked_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_expires" ON "auth_sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_user" ON "auth_sessions" ("id_user") `);
        await queryRunner.query(`CREATE INDEX "idx_users_locked" ON "users" ("locked_until") WHERE (locked_until IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_students_preferred_modality" ON "students" ("preferred_modality") `);
        await queryRunner.query(`CREATE INDEX "idx_students_career" ON "students" ("career") `);
        await queryRunner.query(`CREATE INDEX "idx_scheduled_sessions_composite" ON "scheduled_sessions" ("id_availability", "id_tutor") `);
        await queryRunner.query(`CREATE INDEX "idx_scheduled_sessions_id_session" ON "scheduled_sessions" ("id_session") `);
        await queryRunner.query(`CREATE INDEX "idx_scheduled_sessions_id_availability" ON "scheduled_sessions" ("id_availability") `);
        await queryRunner.query(`CREATE INDEX "idx_scheduled_sessions_id_tutor" ON "scheduled_sessions" ("id_tutor") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_expiry" ON "sessions" ("confirmation_expires_at", "status") WHERE (status = 'PENDING_TUTOR_CONFIRMATION'::session_status_enum)`);
        await queryRunner.query(`CREATE INDEX "idx_modification_requests_pending_active" ON "session_modification_requests" ("expires_at", "status") WHERE (status = 'PENDING'::modification_status_enum)`);
        await queryRunner.query(`CREATE INDEX "idx_modification_requests_requested_at" ON "session_modification_requests" ("requested_at") `);
        await queryRunner.query(`CREATE INDEX "idx_modification_requests_expires_at" ON "session_modification_requests" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_modification_requests_status" ON "session_modification_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_modification_requests_responder" ON "session_modification_requests" ("responded_by") `);
        await queryRunner.query(`CREATE INDEX "idx_modification_requests_requester" ON "session_modification_requests" ("requested_by") `);
        await queryRunner.query(`CREATE INDEX "idx_modification_requests_session" ON "session_modification_requests" ("id_session") `);
        await queryRunner.query(`CREATE INDEX "idx_student_participate_session_status_arrival" ON "student_participate_session" ("arrival_time", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_student_participate_session_arrival_time" ON "student_participate_session" ("arrival_time") `);
        await queryRunner.query(`CREATE INDEX "idx_student_participate_session_status" ON "student_participate_session" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_student_participate_session_session" ON "student_participate_session" ("id_session") `);
        await queryRunner.query(`CREATE INDEX "idx_student_participate_session_student" ON "student_participate_session" ("id_student") `);
        await queryRunner.query(`CREATE INDEX "idx_answers_evaluated_at" ON "answers" ("evaluated_at") `);
        await queryRunner.query(`CREATE INDEX "idx_answers_evaluation_id" ON "answers" ("evaluation_id") `);
        await queryRunner.query(`CREATE INDEX "idx_answers_id_session" ON "answers" ("id_session") `);
        await queryRunner.query(`CREATE INDEX "idx_answers_id_student" ON "answers" ("id_student") `);
        await queryRunner.query(`CREATE INDEX "idx_questions_questionnaire_version" ON "questions" ("questionnaire_version") `);
        await queryRunner.query(`CREATE INDEX "idx_questions_display_order" ON "questions" ("display_order") `);
        await queryRunner.query(`CREATE INDEX "idx_questions_is_active" ON "questions" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_questions_aspect" ON "questions" ("aspect") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_session" FOREIGN KEY ("id_session") REFERENCES "auth_sessions"("id_session") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "fk_verify_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "fk_reset_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "fk_auth_session_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dashboard_banner" ADD CONSTRAINT "fk_dashboard_banner_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users"("id_user") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "fk_students_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" ADD CONSTRAINT "fk_tutor_subject_subject" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" ADD CONSTRAINT "fk_tutor_subject_tutor" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutors" ADD CONSTRAINT "fk_tutor_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" ADD CONSTRAINT "fk_tha_availability" FOREIGN KEY ("id_availability") REFERENCES "availability"("id_availability") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" ADD CONSTRAINT "fk_tha_tutor" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "fk_scheduled_sessions_session" FOREIGN KEY ("id_session") REFERENCES "sessions"("id_session") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "fk_scheduled_sessions_availability" FOREIGN KEY ("id_availability") REFERENCES "availability"("id_availability") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "fk_scheduled_sessions_tutor" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_subject" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_tutor" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ADD CONSTRAINT "fk_modification_requests_responder" FOREIGN KEY ("responded_by") REFERENCES "users"("id_user") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ADD CONSTRAINT "fk_modification_requests_requester" FOREIGN KEY ("requested_by") REFERENCES "users"("id_user") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "session_modification_requests" ADD CONSTRAINT "fk_modification_requests_session" FOREIGN KEY ("id_session") REFERENCES "sessions"("id_session") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ADD CONSTRAINT "fk_student_participate_session_session" FOREIGN KEY ("id_session") REFERENCES "sessions"("id_session") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ADD CONSTRAINT "fk_student_participate_session_student" FOREIGN KEY ("id_student") REFERENCES "students"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "fk_answers_student_session" FOREIGN KEY ("id_student", "id_session") REFERENCES "student_participate_session"("id_student","id_session") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "fk_answers_question" FOREIGN KEY ("id_question") REFERENCES "questions"("id_question") ON DELETE RESTRICT ON UPDATE CASCADE`);
    }

}
