import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateStudentsTable1771551726237 implements MigrationInterface {
    name = 'CreateStudentsTable1771551726237'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tutors" DROP CONSTRAINT "fk_tutor_user"`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" DROP CONSTRAINT "fk_tutor_subject_tutor"`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" DROP CONSTRAINT "fk_tutor_subject_subject"`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "fk_auth_session_user"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "fk_password_reset_user"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "fk_email_verify_user"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "fk_audit_user"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "fk_audit_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_sessions_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_auth_sessions_expires"`);
        await queryRunner.query(`DROP INDEX "public"."idx_password_reset_expires"`);
        await queryRunner.query(`DROP INDEX "public"."idx_email_verify_expires"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_failed_logins"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_role_check"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_status_check"`);
        await queryRunner.query(`CREATE TABLE "questions" ("id_question" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, CONSTRAINT "PK_42f7d8f0cb5a36bdb8873474f73" PRIMARY KEY ("id_question"))`);
        await queryRunner.query(`CREATE TABLE "answers" ("id_question" uuid NOT NULL, "id_student" uuid NOT NULL, "id_session" uuid NOT NULL, "score" smallint, CONSTRAINT "PK_c1417fe520634f4cb323644d9f8" PRIMARY KEY ("id_question", "id_student", "id_session"))`);
        await queryRunner.query(`CREATE TYPE "public"."student_participate_session_status_enum" AS ENUM('REGISTERED', 'ATTENDED', 'ABSENT', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "student_participate_session" ("id_student" uuid NOT NULL, "id_session" uuid NOT NULL, "status" "public"."student_participate_session_status_enum", "comment" text, CONSTRAINT "PK_bd04f2a8d91eafd52dd6d937527" PRIMARY KEY ("id_student", "id_session"))`);
        await queryRunner.query(`CREATE TYPE "public"."sessions_type_enum" AS ENUM('INDIVIDUAL', 'GROUP')`);
        await queryRunner.query(`CREATE TYPE "public"."sessions_modality_enum" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`CREATE TYPE "public"."sessions_status_enum" AS ENUM('SCHEDULED', 'CONFIRMED', 'CANCELLED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id_session" uuid NOT NULL DEFAULT uuid_generate_v4(), "id_tutor" uuid NOT NULL, "id_subject" uuid NOT NULL, "scheduled_date" date NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "type" "public"."sessions_type_enum", "modality" "public"."sessions_modality_enum", "status" "public"."sessions_status_enum", "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_858bc8fe367b57b2de3ad3316bd" PRIMARY KEY ("id_session"))`);
        await queryRunner.query(`CREATE TABLE "scheduled_sessions" ("id_tutor" uuid NOT NULL, "id_availability" uuid NOT NULL, "id_session" uuid, CONSTRAINT "REL_6df0305f4681b7af345413ee6d" UNIQUE ("id_session"), CONSTRAINT "PK_01760f690a68a7095a22ff8475e" PRIMARY KEY ("id_tutor", "id_availability"))`);
        await queryRunner.query(`CREATE TABLE "availability" ("id_availability" uuid NOT NULL DEFAULT uuid_generate_v4(), "day_of_week" smallint NOT NULL, "start_time" TIME NOT NULL, CONSTRAINT "PK_74c354f1c8d40ea5ca04a281895" PRIMARY KEY ("id_availability"))`);
        await queryRunner.query(`CREATE TYPE "public"."tutor_have_availability_modality_enum" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`CREATE TABLE "tutor_have_availability" ("id_tutor" uuid NOT NULL, "id_availability" uuid NOT NULL, "modality" "public"."tutor_have_availability_modality_enum", CONSTRAINT "PK_1081a75d607ac74f1c1daac8e70" PRIMARY KEY ("id_tutor", "id_availability"))`);
        await queryRunner.query(`CREATE TABLE "student_interested_subject" ("id_student" uuid NOT NULL, "id_subject" uuid NOT NULL, CONSTRAINT "PK_7669f9531866a26d5eecf993e01" PRIMARY KEY ("id_student", "id_subject"))`);
        await queryRunner.query(`CREATE TYPE "public"."students_preferred_modality_enum" AS ENUM('PRES', 'VIRT')`);
        await queryRunner.query(`CREATE TABLE "students" ("id_user" uuid NOT NULL, "career" character varying(100), "preferred_modality" "public"."students_preferred_modality_enum", CONSTRAINT "PK_b559710a42d2bf3b49062750132" PRIMARY KEY ("id_user"))`);
        await queryRunner.query(`ALTER TABLE "subject" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD "last_activity_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('STUDENT', 'TUTOR', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'PENDING', 'BLOCKED')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ALTER COLUMN "id_user" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'ACCOUNT_CREATED', 'EMAIL_VERIFIED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'SESSION_CREATED', 'SESSION_REFRESHED', 'SESSION_REVOKED', 'SESSION_EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" "public"."audit_logs_action_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "result"`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_result_enum" AS ENUM('SUCCESS', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "result" "public"."audit_logs_result_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_c570b5fef77654bf9ff41b00624" FOREIGN KEY ("id_question") REFERENCES "questions"("id_question") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "answers" ADD CONSTRAINT "FK_a34388d454fcfb0f90b6ff4b515" FOREIGN KEY ("id_student", "id_session") REFERENCES "student_participate_session"("id_student","id_session") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ADD CONSTRAINT "FK_049762489deb773f79eaa38e43b" FOREIGN KEY ("id_student") REFERENCES "students"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" ADD CONSTRAINT "FK_fe4bfc9c9d6054067ca1490a5a3" FOREIGN KEY ("id_session") REFERENCES "sessions"("id_session") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_a9ed75a85efcadd71bbc8be5ee5" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_412317c2f4613f7f852ec0eaf31" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "FK_0d4b04a7079847403da2f7587cd" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "FK_c862ed5f3d65ee0ab41aa0c6fd6" FOREIGN KEY ("id_availability") REFERENCES "availability"("id_availability") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" ADD CONSTRAINT "FK_6df0305f4681b7af345413ee6d7" FOREIGN KEY ("id_session") REFERENCES "sessions"("id_session") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" ADD CONSTRAINT "FK_6fe15be85a142eb123e22c9d043" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" ADD CONSTRAINT "FK_1b75a22ce69dd4ad3eafb4ccf2f" FOREIGN KEY ("id_availability") REFERENCES "availability"("id_availability") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutors" ADD CONSTRAINT "FK_8325796beb64a4c91dfe1c3955b" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" ADD CONSTRAINT "FK_a11475cea15ad0c4faa5e7ade16" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" ADD CONSTRAINT "FK_e2a77eea1cf449be7efe7147b31" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_interested_subject" ADD CONSTRAINT "FK_fa1094cb4cc067b455c39fa4ac8" FOREIGN KEY ("id_student") REFERENCES "students"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_interested_subject" ADD CONSTRAINT "FK_36ba92aa42c5d6d14eca4ac8028" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_b559710a42d2bf3b49062750132" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "FK_b266e81e60e8c49ae2eb7c46d27" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_a440159fb2d7b579070f5206044" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_8e4afd15aa5933a0aef14ddc743" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_1aabbc22a9f345c55ee39bf5daf" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_25d884c2a4c2cb629dc994e82d1" FOREIGN KEY ("id_session") REFERENCES "auth_sessions"("id_session") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_25d884c2a4c2cb629dc994e82d1"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_1aabbc22a9f345c55ee39bf5daf"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_8e4afd15aa5933a0aef14ddc743"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_a440159fb2d7b579070f5206044"`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "FK_b266e81e60e8c49ae2eb7c46d27"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_b559710a42d2bf3b49062750132"`);
        await queryRunner.query(`ALTER TABLE "student_interested_subject" DROP CONSTRAINT "FK_36ba92aa42c5d6d14eca4ac8028"`);
        await queryRunner.query(`ALTER TABLE "student_interested_subject" DROP CONSTRAINT "FK_fa1094cb4cc067b455c39fa4ac8"`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" DROP CONSTRAINT "FK_e2a77eea1cf449be7efe7147b31"`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" DROP CONSTRAINT "FK_a11475cea15ad0c4faa5e7ade16"`);
        await queryRunner.query(`ALTER TABLE "tutors" DROP CONSTRAINT "FK_8325796beb64a4c91dfe1c3955b"`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" DROP CONSTRAINT "FK_1b75a22ce69dd4ad3eafb4ccf2f"`);
        await queryRunner.query(`ALTER TABLE "tutor_have_availability" DROP CONSTRAINT "FK_6fe15be85a142eb123e22c9d043"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "FK_6df0305f4681b7af345413ee6d7"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "FK_c862ed5f3d65ee0ab41aa0c6fd6"`);
        await queryRunner.query(`ALTER TABLE "scheduled_sessions" DROP CONSTRAINT "FK_0d4b04a7079847403da2f7587cd"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_412317c2f4613f7f852ec0eaf31"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_a9ed75a85efcadd71bbc8be5ee5"`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" DROP CONSTRAINT "FK_fe4bfc9c9d6054067ca1490a5a3"`);
        await queryRunner.query(`ALTER TABLE "student_participate_session" DROP CONSTRAINT "FK_049762489deb773f79eaa38e43b"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_a34388d454fcfb0f90b6ff4b515"`);
        await queryRunner.query(`ALTER TABLE "answers" DROP CONSTRAINT "FK_c570b5fef77654bf9ff41b00624"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "result"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_result_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "result" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ALTER COLUMN "id_user" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP COLUMN "last_activity_at"`);
        await queryRunner.query(`ALTER TABLE "subject" DROP COLUMN "is_active"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_preferred_modality_enum"`);
        await queryRunner.query(`DROP TABLE "student_interested_subject"`);
        await queryRunner.query(`DROP TABLE "tutor_have_availability"`);
        await queryRunner.query(`DROP TYPE "public"."tutor_have_availability_modality_enum"`);
        await queryRunner.query(`DROP TABLE "availability"`);
        await queryRunner.query(`DROP TABLE "scheduled_sessions"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_modality_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_type_enum"`);
        await queryRunner.query(`DROP TABLE "student_participate_session"`);
        await queryRunner.query(`DROP TYPE "public"."student_participate_session_status_enum"`);
        await queryRunner.query(`DROP TABLE "answers"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_status_check" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PENDING'::character varying, 'BLOCKED'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_role_check" CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'TUTOR'::character varying, 'ADMIN'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_failed_logins" ON "audit_logs" ("action", "ip_address", "created_at") WHERE ((action)::text = 'LOGIN_FAILED'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_audit_created_at" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_user" ON "audit_logs" ("id_user") `);
        await queryRunner.query(`CREATE INDEX "idx_email_verify_expires" ON "email_verification_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_password_reset_expires" ON "password_reset_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_expires" ON "auth_sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_auth_sessions_user" ON "auth_sessions" ("id_user") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_session" FOREIGN KEY ("id_session") REFERENCES "auth_sessions"("id_session") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "fk_email_verify_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "fk_password_reset_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "fk_auth_session_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" ADD CONSTRAINT "fk_tutor_subject_subject" FOREIGN KEY ("id_subject") REFERENCES "subject"("id_subject") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutor_impart_subject" ADD CONSTRAINT "fk_tutor_subject_tutor" FOREIGN KEY ("id_tutor") REFERENCES "tutors"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tutors" ADD CONSTRAINT "fk_tutor_user" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
