import { BadRequestException, ForbiddenException } from '@nestjs/common';
import { TutorsController } from './tutor.controller';
import { TutorService } from '../services/tutor.service';
import { UserRole } from '../../users/entities/user.entity';
import { UserService } from '../../users/services/users.service';
import { CloudinaryService } from '../../cloudinary/services/cloudinary.service';

describe('TutorsController', () => {
  let controller: TutorsController;
  let tutorService: jest.Mocked<
    Pick<
      TutorService,
      | 'getTutorHoursStatus'
      | 'getAvatarUploadSignature'
      | 'validateAvatarUrl'
      | 'confirmAvatarUpload'
    >
  >;
  let cloudinaryService: jest.Mocked<
    Pick<CloudinaryService, 'isValidCloudinaryUrl'>
  >;

  beforeEach(() => {
    tutorService = {
      getTutorHoursStatus: jest.fn(),
      getAvatarUploadSignature: jest.fn(),
      validateAvatarUrl: jest.fn(),
      confirmAvatarUpload: jest.fn(),
    };

    cloudinaryService = {
      isValidCloudinaryUrl: jest.fn(),
    };

    controller = new TutorsController(
      tutorService as unknown as TutorService,
      {} as UserService,
      cloudinaryService as unknown as CloudinaryService,
    );
  });

  describe('getTutorHoursStatus', () => {
    it('should allow ADMIN to query any tutor id', async () => {
      const tutorId = '11111111-1111-1111-1111-111111111111';
      const adminUser = {
        idUser: '22222222-2222-2222-2222-222222222222',
        role: UserRole.ADMIN,
      } as any;

      const expected = {
        tutorId,
        weeklyHoursUsed: 6,
        weeklyHoursRemaining: 2,
        usedPercentage: 75,
        remainingPercentage: 25,
        consultedAt: new Date().toISOString(),
      };

      tutorService.getTutorHoursStatus.mockResolvedValue(expected as any);

      const result = await controller.getTutorHoursStatus(adminUser, tutorId);

      expect(tutorService.getTutorHoursStatus).toHaveBeenCalledWith(tutorId);
      expect(result).toEqual(expected);
    });

    it('should allow TUTOR to query own id', async () => {
      const tutorId = '33333333-3333-3333-3333-333333333333';
      const tutorUser = {
        idUser: tutorId,
        role: UserRole.TUTOR,
      } as any;

      const expected = {
        tutorId,
        weeklyHoursUsed: 3.5,
        weeklyHoursRemaining: 4.5,
        usedPercentage: 43.75,
        remainingPercentage: 56.25,
        consultedAt: new Date().toISOString(),
      };

      tutorService.getTutorHoursStatus.mockResolvedValue(expected as any);

      const result = await controller.getTutorHoursStatus(tutorUser, tutorId);

      expect(tutorService.getTutorHoursStatus).toHaveBeenCalledWith(tutorId);
      expect(result).toEqual(expected);
    });

    it('should reject TUTOR querying a different tutor id', async () => {
      const tutorUser = {
        idUser: '44444444-4444-4444-4444-444444444444',
        role: UserRole.TUTOR,
      } as any;

      await expect(
        controller.getTutorHoursStatus(
          tutorUser,
          '55555555-5555-5555-5555-555555555555',
        ),
      ).rejects.toThrow(ForbiddenException);

      await expect(
        controller.getTutorHoursStatus(
          tutorUser,
          '55555555-5555-5555-5555-555555555555',
        ),
      ).rejects.toMatchObject({
        response: {
          errorCode: 'PERMISSION_01',
          message: 'Solo puedes consultar tus propias horas',
        },
      });

      expect(tutorService.getTutorHoursStatus).not.toHaveBeenCalled();
    });
  });

  describe('avatar flow', () => {
    it('should return the avatar signature generated by the service', async () => {
      const tutorId = '66666666-6666-6666-6666-666666666666';
      const signature = {
        timestamp: '1710000000',
        signature: 'signature',
        api_key: 'api-key',
        cloud_name: 'sgt-cloud',
        folder: 'tutors/66666666-6666-6666-6666-666666666666',
        public_id: 'tutors/66666666-6666-6666-6666-666666666666/avatar',
      };

      tutorService.getAvatarUploadSignature.mockResolvedValue(signature as any);

      const result = await controller.getAvatarSignature(tutorId);

      expect(tutorService.getAvatarUploadSignature).toHaveBeenCalledWith(
        tutorId,
      );
      expect(result).toEqual(signature);
    });

    it('should confirm avatar upload when the url is valid and belongs to the tutor', async () => {
      const tutorId = '77777777-7777-7777-7777-777777777777';
      const dto = {
        secure_url:
          'https://res.cloudinary.com/sgt-cloud/image/upload/v1/tutors/77777777-7777-7777-7777-777777777777/avatar.jpg',
        public_id: 'tutors/77777777-7777-7777-7777-777777777777/avatar',
      };

      cloudinaryService.isValidCloudinaryUrl.mockReturnValue(true);
      tutorService.validateAvatarUrl.mockReturnValue(true);
      tutorService.confirmAvatarUpload.mockResolvedValue({
        message: 'Avatar actualizado correctamente',
      });

      const result = await controller.confirmAvatarUpload(tutorId, dto as any);

      expect(cloudinaryService.isValidCloudinaryUrl).toHaveBeenCalledWith(
        dto.secure_url,
      );
      expect(tutorService.validateAvatarUrl).toHaveBeenCalledWith(
        dto.secure_url,
        tutorId,
      );
      expect(tutorService.confirmAvatarUpload).toHaveBeenCalledWith(
        tutorId,
        dto.secure_url,
        dto.public_id,
      );
      expect(result).toEqual({
        message: 'Avatar actualizado correctamente',
      });
    });

    it('should reject non-cloudinary urls', async () => {
      cloudinaryService.isValidCloudinaryUrl.mockReturnValue(false);

      await expect(
        controller.confirmAvatarUpload('88888888-8888-8888-8888-888888888888', {
          secure_url: 'https://example.com/avatar.jpg',
          public_id: 'tutors/88888888-8888-8888-8888-888888888888/avatar',
        } as any),
      ).rejects.toMatchObject({
        response: {
          errorCode: 'VALIDATION_02',
          message: 'URL no es de Cloudinary',
        },
      });

      expect(tutorService.validateAvatarUrl).not.toHaveBeenCalled();
      expect(tutorService.confirmAvatarUpload).not.toHaveBeenCalled();
    });

    it('should reject avatar urls that do not belong to the tutor', async () => {
      cloudinaryService.isValidCloudinaryUrl.mockReturnValue(true);
      tutorService.validateAvatarUrl.mockReturnValue(false);

      await expect(
        controller.confirmAvatarUpload('99999999-9999-9999-9999-999999999999', {
          secure_url:
            'https://res.cloudinary.com/sgt-cloud/image/upload/v1/tutors/other/avatar.jpg',
          public_id: 'tutors/other/avatar',
        } as any),
      ).rejects.toMatchObject({
        response: {
          errorCode: 'VALIDATION_03',
          message: 'Avatar no pertenece a este tutor',
        },
      });

      expect(tutorService.confirmAvatarUpload).not.toHaveBeenCalled();
    });
  });
});
